### ISSUE TITLE
Causing "desktop" system performance issues

### ISSUE THREAD

**Issue by xenoterracide** [kpcyrd/libredefender#12]
So I decided to install libre defender over just ClamAV being interested in the goal of being desktop-oriented. Unfortunately, I've found that on my laptop, it starts as soon as I get up (probably a system timer start on resume thing). When it runs, it uses so much CPU (io?) that my system... lags. Not to the point it's frozen, but to where it's obnoxious to use.  All 8 cores of my CPU are maxed, and my IO seems to be running high. I checked htop/iotop, and it appears to be nice-ed and ionice-ed properly. So to some extent, it could be argued this is a kernel problem, a Wayland problem, etc. However, no other application causes this problem, not even when I'm doing intensive software development, only when it's doing a scan.

My first thought on resolving this? let me limit it to one core. I doubt, even if one core is running at max, that it causes my system to be unusable.

```
Linux manjaro 5.10.60-1-MANJARO #1 SMP PREEMPT Wed Aug 18 08:02:07 UTC 2021 x86_64 GNU/Linux
```

NOTE: This is a Thinkpad Carbon X1 Gen 8 (model released 2020), and I upgraded everything to the Max. Generally speaking, performance issues shouldn't be in its vocabulary.

P.S. Your README shows an example config file, but not where it goes ;).

**Comment by kpcyrd** [comment]
hi!

I've documented the config file location in the readme now, thanks for pointing it out!

I'm wondering if this is either a heat or a ram problem, both of them could cause the system to lag, either because the cpu is clocking down or because it's swapping some of the system memory to disk.

Can you check if the system is swapping during the scan or if there's anything in `dmesg`?

Thanks!

**Comment by xenoterracide** [comment]
I can tell you there was swap being used, but it wasn't swapping to disk. I have 16G of zram, and all the swap was going into that. The machine was definitely getting hot, so it could be that too...

right now it's running, not particularly running into this issue though (maybe because the CPU is clocked down and on battery...)


```Chip: iwlwifi_1-virtual-0
Adapter: Virtual device
  temp1: 48.0 C
Chip: ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
  in0: +0.00 V (min = +0.00 V, max = +0.00 V)
Chip: pch_cannonlake-virtual-0
Adapter: Virtual device
  temp1: 62.0 C
Chip: BAT0-acpi-0
Adapter: ACPI interface
  in0: +15.78 V
Chip: ucsi_source_psy_USBC000:002-isa-0000
Adapter: ISA adapter
  in0: +0.00 V (min = +0.00 V, max = +0.00 V)
Chip: coretemp-isa-0000
Adapter: ISA adapter
  Package id 0: 63.0 C
  Core 0: 62.0 C
  Core 1: 58.0 C
  Core 2: 62.0 C
  Core 3: 63.0 C
Chip: thinkpad-isa-0000
Adapter: ISA adapter
  fan1: 4622 RPM
  temp1: 62.0 C
```

checking for the older boot

**Comment by kpcyrd** [comment]
0.4.0 contains a change that allows opting into single-threaded scanning! :)

**Comment by xenoterracide** [comment]
I haven't noticed any issues since making it single threaded a couple of weeks ago. Seems good, I'll open a new issue if it's not. I might suggest that since this is for desktops you might make 1 or 2 threads the default, or half or 1/4 of the cores or something. That's up to you though.

**Comment by kpcyrd** [comment]
Cool, thanks for following up on the issue!
