### ISSUE TITLE
Fresh install in Arch Linux with v0.40 cannot open /usr/lib/libclamav.so.9

### ISSUE THREAD

**Issue by mruiz42** [kpcyrd/libredefender#18]
libredefender: /usr/lib/libclamav.so.9: no version information available (required by libredefender)
libredefender: /usr/lib/libclamav.so.9: no version information available (required by libredefender)
 ❌ Last scan                 -
 ✅ Threats present           0
 ❌ Signatures                0
 ❌ Signatures updated        -

After running freshclam and starting the freshclam service. Is it a permissions issue? Perhaps this needs to be run as root, is it intended to be run as root? Documentation does not specify.

**Comment by kpcyrd** [comment]
hi, thanks for reporting this! I could reproduce this and solved it by rebuilding the binary and uploading it to Arch Linux as `0.4.0-2`. It's not supposed to run as root, after updating the package it should work, the first scan runs automatically but you might need to re-login to your desktop and verify that xdg-autostart is setup correctly.
