### ISSUE TITLE
Turn scheduled scanning off?

### ISSUE THREAD

**Issue by mannp** [kpcyrd/libredefender#20]
Hi there

Thanks for creating this :)

I am trying to turn scheduled scanning off and have tried commenting out the schedule section, which didn't seem to work and am now trying with a preferred time of between 9am and 9:10am, to see what that does :)

Perhaps I need to delete crontab if I have previously enabled a schedule?

Thanks in advance

**Comment by kpcyrd** [comment]
Starting with 0.5.1:
```
[schedule]
automatic_scans = "off"
```
This would sleep for 24h, check if they're still disabled, and then sleep for 24h again.

The current default if no `[schedule]` section is present:
```
[schedule]
automatic_scans = "daily"
```

**Comment by mannp** [comment]
Thanks for the very quick addition 👍
