### ISSUE TITLE
[Feature request] Don't scan when running on battery

### ISSUE THREAD

**Issue by tongpu** [kpcyrd/libredefender#27]
As I would like to avoid burning CPU cycles while I'm on the go it would be great of the automatic scan would not run when the machine in on battery power.

Should be possible to implement using the [battery](https://docs.rs/battery/latest/battery/) crate.

**Comment by kpcyrd** [comment]
Sounds like a good idea, feel free to send a PR! This should be opt-in though.

**Comment by xenoterracide** [comment]
love this idea, was just coming to report this problem as it will drain my battery from 100% to 10% in 1 hour

**Comment by kpcyrd** [comment]
I'm planning to release this the next few days if it works for everybody.

**Comment by xenoterracide** [comment]
So I've done a little testing between bouts of food poisoning and other problems.... Patch as is doesn't seem to work. I've logged out, logged back in, charged my computer, closed the lid, etc. I just unplugged then opened the lid and libredefender is sitting their running full power on one thread.

```toml
[scan]
concurrency = 1
[schedule]
skip_on_battery = true
```

**Comment by kpcyrd** [comment]
Sorry for being somewhat unavailable, I've invited @tongpu as a maintainer.

**Comment by tongpu** [comment]
@xenoterracide Works on my machine.

When I build from source and configure 
```
[schedule]
skip_on_battery = true
```
unplug my laptop and then run `./target/debug/libredefender scheduler` it's telling me that it's skipping this scan:
```
[2022-04-05T17:13:03Z INFO  libredefender::scan] Initializing with libclamav 0.104.2
[2022-04-05T17:13:03Z INFO  libredefender::schedule] Battery is discharging, skipping this scan
[2022-04-05T17:13:03Z INFO  libredefender::schedule] Sleeping for 24h 0m 0s (2022-04-06 19:13:03 +02:00)...
```
