### ISSUE TITLE
[Feature] improved scheduling

### ISSUE THREAD

**Issue by xenoterracide** [kpcyrd/libredefender#29]
Ok, my preliminary suggestion is actually, remove scheduling and let systemd user (the ones in the home directory) configuration files do this instead. Perhaps it can be streamlined by you in some way. Realistically, I'm just thinking I don't need to run it more than once a week. Honestly *I* probably don't need to run it at all.

**Comment by tongpu** [comment]
I've thought about this as well. The `skip_on_battery` feature would also be something that could have been implemented easily in systems.

**Comment by tongpu** [comment]
I've thought about this as well. The `skip_on_battery` feature would also be something that could have been implemented easily in systems.

**Comment by kpcyrd** [comment]
I'm not sure if there's much I can streamline, you can disable the builtin scheduler with:

```toml
[schedule]
automatic_scans = "off"
```

And run the scans yourself with systemd timers like this:
```ini
# libredefender.timer
[Unit]
Description=libredefender: automatic scans

[Timer]
OnBootSec=1min
OnUnitActiveSec=1h

[Install]
WantedBy=timers.target
```

```ini
# libredefender.service
[Unit]
Description=libredefender: automatic scans

[Service]
User=user
ExecStart=/usr/bin/libredefender scan
```

**Comment by xenoterracide** [comment]
Sure, I was thinking about maybe installing them on first run, but I have to be honest, I can't even remember how `libredefender` gets run in the first place. I was looking at the readme and it doesn't seem to tell me... I don't see a crontab, or a `~/.config/autostart`. I suppose I can look at what the `PKGBUILD` does

**Comment by tongpu** [comment]
The scheduler is being started by `/etc/xdg/autostart/libredefender.desktop` and is then adhering to the rules defined in the configuration.

**Comment by xenoterracide** [comment]
hmm... ok. Well the end goal here was to only have the scan run weekly, but I was thinking that maybe moving to systemd for this would also make your job easier ;)

**Comment by kpcyrd** [comment]
libredefender starts with xdg autostart, if you want to scan weekly you could use something like:
```ini
[Timer]
OnCalendar=weekly
Persistent=true
```
or
```ini
[Timer]
OnCalendar=weekly
Persistent=true
```
there's unfortunately not much I can provide in the package because you'd end up customizing the units to your needs anyway.

**Comment by tongpu** [comment]
I've configured my own service and timer to only run the scan once a week. We could add those to the repo and place them in `/usr/lib/systemd/user` so that people could enable the timer if they want to:

`libredefender-scan.service`
```ini
[Unit]
Description=libredefender scan
# Prevent libredefender from running unless the machine is plugged into power.
ConditionACPower=true

[Service]
Type=oneshot

# Lower CPU and I/O priority.
Nice=19
CPUSchedulingPolicy=batch
IOSchedulingClass=best-effort
IOSchedulingPriority=7
IOWeight=100

Restart=no

ExecStart=libredefender scan
```

`libredefender-scan.timer`
```ini
[Unit]
Description=libredefender scan

[Timer]
OnCalendar=weekly
Persistent=true

[Install]
WantedBy=timers.target
```

**Comment by JoeSz** [comment]
I like tongpu approach. I have a few modification:
- Copy the ```.service``` and ```.timer``` file to ```"/home/[YOUR-USERNAME]/.config/systemd/user/"```
- start with: ```systemctl --user enable --now libredefender-scan.timer```
- check: ```systemctl --user status libredefender-scan.service``` and ```systemctl --user status libredefender-scan.timer```
- ```libredefender-scan.timer```
```php
[Timer]
# This option indicates that missed timer events should be caught up when the system is started or when the timer is enabled.
# If the timer has passed its scheduled activation time while the system was inactive, it will trigger immediately upon system boot or timer activation.
Persistent=true
# This option specifies the delay after system boot before the timer is first triggered.
# In this example, the timer will wait for 15 minutes after the system boots up before activating for the first time.
OnBootSec=15min
# This option determines the time interval between subsequent timer activations.
# Here, the timer will be triggered every 3 days after the initial activation or after the previous timer activation.
OnUnitActiveSec=3d
```
- ```libredefender-scan.service```
```php
# ...
# changed:
Restart=on-failure
# ...
```
