### ISSUE TITLE
[Feature] create an AUR PKGBUILD for git

### ISSUE THREAD

**Issue by xenoterracide** [kpcyrd/libredefender#31]
could use a `libredefender-git` package in order to test things like #27 ;)

**Comment by bjo81** [comment]
Who or what keeps you away from creating one? ;)

**Comment by micwoj92** [comment]
@xenoterracide you will have time to test but not 10 minutes to create this? ;)
https://aur.archlinux.org/packages/libredefender-git
@kpcyrd I added you as comaintaier, feel free to take over if you want.

**Comment by xenoterracide** [comment]
because it would take 30 minutes to create and push that, and I've pretty much got every 15 minutes booked for the next 2 weeks. I'm not even joking. Whereas testing takes 2 commands and waiting until tomorrow. ;)

**Comment by ysf** [comment]
Sometimes you have to take decisions in life. Doing dentals and brushing teeth or doing open source work.

**Comment by AkechiShiro** [comment]
Sorry to intrude on this very technical discussion with an off-topic message, but @xenoterracide, what is your calendar app/software that you're actually using ?

**Comment by xenoterracide** [comment]
I'm using Google calendar combined with usemotion

**Comment by kpcyrd** [comment]
Closing since there's a [-git aur package](https://aur.archlinux.org/packages/libredefender-git) now by @micwoj92 :)
